#!/bin/bash
#PBS -l nodes=2:ppn=12
#PBS -l walltime=00:05:00
#PBS -q debug
#PBS -N 2Nodes
#PBS -j oe

cd /home/uptonm/final-project/nearest-neighbor-parallelized
mpiexec -np 2 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./parallelizedneighbor
